"""
Banco de frases usado para popular `emocao_exemplo`.

Estratégia:
- Cada emoção tem dezenas de exemplos cobrindo frases curtas, médias e longas.
- Frases curtas existem em propósito para que a IA acerte quando o usuário
  escrever "péssima aula" ou "ótima aula" — sem elas, o embedding gravita
  para o domínio acadêmico em vez do sentimento.
- Vocabulário emocional é deliberadamente redundante (péssimo, horrível,
  ruim, chato…) para reforçar o sinal no espaço vetorial.
"""

EMOTION_SEED_EXAMPLES: dict[str, list[str]] = {
    "Alegria": [
        # Frases curtas (alta densidade emocional)
        "Ótima aula.",
        "Aula incrível.",
        "Aula maravilhosa.",
        "Aula excelente.",
        "Professor incrível.",
        "Professora maravilhosa.",
        "Professor excelente.",
        "Adorei a aula.",
        "Amei a aula.",
        "Adorei o professor.",
        "Adorei essa matéria.",
        "Amei o conteúdo.",
        "Passei na prova!",
        "Tirei 10 na prova!",
        "Tirei dez na prova!",
        "Consegui a aprovação!",
        "Prova fácil.",
        "Matéria tranquila.",
        "Curso ótimo.",
        "Curso maravilhoso.",
        "Que aula sensacional.",
        "Que professor fantástico.",
        "Estou muito feliz hoje.",
        "Estou animado com o curso.",
        "Estou motivado com a turma.",
        "Show de aula.",
        "Aula top demais.",
        "Que dia maravilhoso na faculdade.",

        # Frases médias e longas
        "Achei a prova muito fácil e fui muito bem.",
        "A aula foi excelente, a professora é maravilhosa.",
        "Estou muito feliz e motivado com o curso.",
        "Tudo ótimo, nota dez para o material didático.",
        "Achei o conteúdo super tranquilo de entender e adorei.",
        "Finalmente consegui o 10 em Cálculo! Todo o esforço valeu a pena!",
        "Acabei de receber o e-mail de aprovação para a bolsa de iniciação científica, estou radiante!",
        "A sensação de entregar o TCC é indescritível, parece que tirei uma tonelada das costas.",
        "Conheci pessoas incríveis no grupo de estudos hoje e sinto que finalmente encontrei minha turma.",
        "O professor elogiou meu projeto na frente de todos, nunca me senti tão motivado.",
        "Sexta-feira, última aula cancelada e a nota da prova foi acima da média. Melhor dia!",
        "Hoje foi um dia incrível na universidade, aprendi muito.",
        "A aula prática foi fantástica, esse curso é sensacional.",
        "Estou amando o ritmo do semestre, tudo flui muito bem.",
        "Que professor brilhante, a explicação foi clara e divertida.",
        "Tirei a maior nota da turma, estou super orgulhoso do meu desempenho.",
        "Adorei o projeto que vamos fazer, parece desafiador e empolgante.",
        "A monitoria de hoje me ajudou demais, agora entendi o assunto.",
        "Estou empolgado com a feira acadêmica do nosso curso.",
        "Saí da prova com a sensação de que mandei muito bem.",
        "Eu amo essa matéria, é maravilhosa de estudar.",
        "A apresentação do trabalho saiu perfeita, todos elogiaram.",
        "Recebemos um feedback excelente do professor sobre o projeto.",
        "Que bom que escolhi esse curso, acertei demais.",
        "Estou orgulhoso de quanto avancei nesse semestre.",
        "A turma está super engajada e isso me motiva todos os dias.",
        "Foi a melhor aula que tive em todo o semestre, gratidão pelo professor.",
        "Passei em todas as matérias com notas altas, festa!",
        "Que alegria ver meu projeto sendo bem avaliado pela banca.",
    ],

    "Irritado": [
        # Frases curtas (alta densidade emocional)
        "Péssima aula.",
        "Aula péssima.",
        "Aula horrível.",
        "Aula ruim.",
        "Aula chata.",
        "Professor péssimo.",
        "Professora péssima.",
        "Professor horrível.",
        "Professor ruim.",
        "Prova horrível.",
        "Prova péssima.",
        "Prova impossível.",
        "Matéria horrível.",
        "Que aula horrorosa.",
        "Odiei a aula.",
        "Odiei a prova.",
        "Detesto essa matéria.",
        "Que merda essa prova.",
        "Que ódio dessa matéria.",
        "Estou com raiva da turma.",
        "Estou irritado com o curso.",
        "Estou frustrado com a nota.",
        "Estou furioso com o professor.",
        "Que desgraça de prova.",
        "Tirei zero na prova.",
        "Fui muito mal na prova.",
        "Reprovei na prova.",
        "Rodei na disciplina.",
        "Tô esgotado.",
        "Tô exausto.",
        "Tô estressado.",
        "Que ansiedade essa semana.",
        "Tô em pânico com o TCC.",
        "Que decepção esse curso.",
        "Que vergonha de aula.",
        "Isso é ridículo.",
        "Isso é lamentável.",
        "Curso lixo.",
        "Aula lixo.",

        # Frases médias e longas
        "Achei a prova muito difícil e fui muito mal.",
        "A aula foi péssima, a professora não ensina bem.",
        "Estou muito frustrado e triste com o curso.",
        "Tudo horrível, odiei o material didático.",
        "Achei o conteúdo impossível de entender, muito complicado.",
        "Não aguento mais esse semestre, sinto que por mais que eu estude, a nota nunca vem.",
        "Passei a noite em claro revisando o conteúdo e, na hora da prova, deu um branco total.",
        "É muito desanimador ver todo mundo conseguindo estágio enquanto eu nem recebo resposta dos currículos.",
        "O professor ignorou todas as minhas dúvidas e ainda foi sarcástico na frente da sala inteira.",
        "Minha família coloca muita pressão em cima de mim, mas eu nem sei se é esse curso que eu quero de verdade.",
        "O portal da faculdade caiu bem na hora de enviar o trabalho final e agora vou ficar com zero.",
        "A aula de hoje foi um desastre, ninguém entendeu nada do que o professor falou.",
        "Que prova ridícula, cobraram coisas que nem caíram no estudo.",
        "Tô extremamente decepcionado com o nível dessa disciplina.",
        "Esse professor é incompetente, não consegue explicar nada direito.",
        "A burocracia da faculdade é insuportável, parece que querem dificultar tudo.",
        "Fiquei a madrugada inteira estudando e olha o que aconteceu, fui mal de novo.",
        "Cansei desse semestre, não tenho mais paciência para nada.",
        "Hoje saí da sala com vontade de chorar de tanta frustração.",
        "Reprovaram metade da turma por causa de uma prova injusta.",
        "Esse curso está acabando comigo, não durmo mais direito.",
        "O professor humilhou um colega na frente de todo mundo, achei um absurdo.",
        "Estou no limite, mais um trabalho atrasado e vou pirar.",
        "Tô com ansiedade só de pensar na semana de provas que vem aí.",
        "É frustrante perder um semestre inteiro por causa de uma disciplina mal planejada.",
        "Esse professor é o pior que já tive, simplesmente não dá.",
        "Não estou aguentando mais a pressão, parece que tudo está dando errado.",
        "Que matéria chata, perco a paciência só de entrar na sala.",
        "A coordenação não resolve nada, fico horas esperando uma resposta.",
        "Aula sem nexo, professor enrolado e sala lotada — receita do desastre.",
    ],

    "Neutro": [
        # Frases curtas (avisos/informativos)
        "Aula hoje no laboratório.",
        "Tem prova amanhã.",
        "Aula no bloco C.",
        "Horário normal de aula.",
        "Matéria padrão.",
        "Comunicado da coordenação.",
        "Biblioteca aberta até as 22h.",
        "Informativo da secretaria.",
        "Hoje tem monitoria.",
        "Trabalho para a próxima semana.",

        # Frases médias e longas (factuais)
        "Achei a prova mais ou menos, na média.",
        "A aula foi normal, a professora deu o conteúdo padrão.",
        "Estou indiferente com o curso, normal.",
        "Material didático regular, sem grandes problemas.",
        "Achei o conteúdo razoável, nem fácil nem difícil.",
        "Hoje tem aula de inglês na faculdade.",
        "O professor passou um trabalho para a próxima semana.",
        "Amanhã temos prova de banco de dados.",
        "Apenas assistindo a aula, sem opiniões fortes.",
        "Hoje o dia foi padrão, nada de diferente.",
        "A aula de amanhã será realizada no laboratório do bloco C, a partir das 19 horas.",
        "O período de renovação de matrícula começa na próxima segunda-feira via portal do aluno.",
        "Preciso passar na biblioteca para devolver o livro de anatomia antes que vença o prazo.",
        "O currículo do curso foi atualizado e agora inclui a disciplina de Inteligência Artificial.",
        "Vou almoçar no restaurante universitário e depois seguir para a monitoria de física.",
        "A palestra sobre carreira acadêmica terá duração de duas horas com emissão de certificado.",
        "A entrega do relatório está marcada para sexta-feira.",
        "A coordenação enviou um e-mail informando sobre a reunião do colegiado.",
        "As inscrições para o intercâmbio abrem em junho.",
        "Hoje a aula foi sobre algoritmos de ordenação.",
        "Vamos ter uma palestra com um profissional do mercado na próxima semana.",
        "A faculdade vai estar fechada no feriado nacional.",
        "Vou começar a fazer iniciação científica no próximo semestre.",
        "O laboratório de informática fica no segundo andar do bloco B.",
        "A prova substitutiva acontece duas semanas após a prova oficial.",
        "O sistema acadêmico foi atualizado durante o final de semana.",
        "Os horários de atendimento da secretaria são das 8h às 18h.",
        "Aula de hoje começou às 19h conforme o cronograma.",
        "O TCC precisa ter no mínimo 30 páginas segundo o regulamento.",
        "Trocaram a sala da minha aula para o bloco vermelho.",
        "Hoje a aula é sobre estruturas de dados.",
        "O professor disponibilizou o material da aula no portal.",
        "Vai ter um simpósio acadêmico aberto a todos os cursos.",
        "Recebi a confirmação da matrícula nas optativas.",
        "A biblioteca fechou mais cedo essa semana por causa do evento.",
        "A próxima reunião do grupo de estudos é na quinta-feira.",
        "Encontrei o pessoal do projeto integrador na cantina.",
        "A nota da atividade ficou disponível no portal.",
        "Vou pegar o ônibus da faculdade depois da aula.",
        "A monitoria de cálculo é toda terça à tarde.",

        # Frases com vocabulário potencialmente ambíguo (professor, aula, matéria)
        # — necessárias para que o KNN não as confunda com elogios.
        "Hoje tem aula de cálculo.",
        "Hoje tem aula de física.",
        "Hoje tem aula de algoritmos.",
        "Professor passou um exercício.",
        "A professora passou os slides.",
        "Professor falou sobre o conteúdo da matéria.",
        "Professor explicou os tópicos da prova.",
        "A aula foi sobre ponteiros e alocação de memória.",
        "A matéria de hoje foi estrutura de dados.",
        "O professor comentou sobre as datas de entrega.",
        "Hoje a aula de inglês foi normal.",
        "O professor falou sobre o TCC.",
        "Aula sobre banco de dados nesta semana.",
        "A professora vai cobrar o trabalho semana que vem.",
    ],
}
